# Generated by Django 5.1.3 on 2024-11-17 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('time_since_injury', models.FloatField(help_text='Time in hours since the injury occurred')),
                ('gcs', models.IntegerField(help_text='Glasgow Coma Scale (3-15)')),
                ('gos', models.IntegerField(help_text='Glasgow Outcome Scale (1-5)')),
                ('prognosis', models.CharField(blank=True, help_text='Predicted outcome (auto-generated)', max_length=50)),
            ],
        ),
    ]
